### PR TITLE
Update snap7_client.cpp

### PR DESCRIPTION
**Pull request by Sinclair81**
Fix for Issue #1

### CODE REVIEW

**Comment by Sinclair81** [comment]
Data I/O Lean functions
Added DBReadSync(), DBRead(), DBWriteSync(), DBWrite()
Change name from ReadPromiseWorker to ReadAreaPromiseWorker,
WritePromiseWorker to WriteAreaPromiseWorker,
ReadCallbackWorker to ReadAreaCallbackWorker,
WriteCallbackWorker to WriteAreaCallbackWorker

**Comment by fabioriva** [comment]
Hi Sinclair, due to other work commitments I currently don't have time to review your pull request.
What I can do is invite you as a contributor so you can submit changes to the repository.
Are you interested? Let me know.

**Comment by Sinclair81** [comment]
Hi Fabio,
I would really like to do that.
But what do we do with the package in NPM? It has to be uploaded there so that you can install it via NPM.
The build process worked without any problems on my Homebride test device. From there I always upload my plugins to NPM after the build.

**Comment by fabioriva** [comment]
> Hi Fabio, I would really like to do that. But what do we do with the package in NPM? It has to be uploaded there so that you can install it via NPM. The build process worked without any problems on my Homebride test device. From there I always upload my plugins to NPM after the build.

I can add you as a maintainer of the npm package. In this way you are enabled to push new version..

**Pull request merged**
